sonar.sources=apps,packages,docs

sonar.tests=apps,packages
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/.turbo/**,**/coverage/**,bun.lock,packages/db/drizzle/**,**/*.d.ts

sonar.cpd.exclusions=packages/db/drizzle/**

sonar.sourceEncoding=UTF-8
